version: "2"
services:

  # nginx web server
  server:
    build: ./build/server
    container_name: server
    extra_hosts:
      conjur-master: $CONJUR_MASTER_HOST_IP
    ports:
      - "9080:80"
      - "9443:443"
    volumes:
      - ./server_content:/server_content:z
  
  # curl web client
  client:
    build: ./build/client
    container_name: client
    entrypoint: "sleep infinity"
    environment:
      TERM: xterm
    extra_hosts:
      conjur-master: $CONJUR_MASTER_HOST_IP
  
  # Service for generating our root and intermediate CA
  ca:
    build: ./build/ca
    volumes: 
      - ./ca:/root
