#!/bin/bash 
set -eo pipefail

source ./cicd-demo.conf

main() {
  load_policy
  generate_identity_files
  docker-compose up -d
  initialize_client_node
  clear
  echo "cd to /demo..."
  docker exec -it client_node bash
}

load_policy() {

  # login as admin
  docker exec $CLI_CONTAINER_NAME bash -c "echo yes | conjur init -u $CONJUR_APPLIANCE_URL -a $CONJUR_ACCOUNT --force=true"
  docker exec $CLI_CONTAINER_NAME conjur authn login -u admin -p $CONJUR_ADMIN_PASSWORD

  # copy policy to CLI container
  docker cp ./policy/cicd-policy.yml $CLI_CONTAINER_NAME:/policy/

  # load policy
  docker exec $CLI_CONTAINER_NAME \
	conjur policy load root /policy/cicd-policy.yml

  # initialize variables
  docker exec $CLI_CONTAINER_NAME \
	conjur variable values add cicd-secrets/test-db-username ThisIsTheTESTDBuserName
  docker exec $CLI_CONTAINER_NAME \
	conjur variable values add cicd-secrets/test-db-password 10938471084710238470973
  docker exec $CLI_CONTAINER_NAME \
	conjur variable values add cicd-secrets/prod-db-username ThisIsThePRODDBuserName
  docker exec $CLI_CONTAINER_NAME \
	conjur variable values add cicd-secrets/prod-db-password aoiuaspduperjqkjnsoudoo
}

generate_identity_files() {
  CONJUR_AUTHN_API_KEY=$(docker exec $CLI_CONTAINER_NAME conjur host rotate_api_key --host $CONJUR_AUTHN_LOGIN)

  # create configuration and identity files (AKA conjurize the host)
  echo "Generating identity file..."
  cat <<IDENTITY_EOF | tee conjur.identity
machine $CONJUR_APPLIANCE_URL/authn
  login host/$CONJUR_AUTHN_LOGIN
  password $CONJUR_AUTHN_API_KEY
IDENTITY_EOF

  echo
  echo "Generating host configuration file..."
  cat <<CONF_EOF | tee conjur.conf
---
appliance_url: $CONJUR_APPLIANCE_URL
account: $CONJUR_ACCOUNT
netrc_path: "/etc/conjur.identity"
cert_file: "/etc/conjur-$CONJUR_ACCOUNT.pem"
CONF_EOF
}

initialize_client_node() {
  docker cp $CONJUR_CERT_FILE client_node:/etc
  docker cp ./conjur.conf client_node:/etc
  docker cp ./conjur.identity client_node:/etc
  docker exec client_node chmod 400 /etc/conjur.identity
  rm ./conjur*
  docker exec -it client_node terraform init
  docker cp ./demo/. client_node:/demo/
}

main $@
