#!/bin/bash
echo "Deleting 4 pets.."
curl -XDELETE $CONJUR_MASTER_HOST_NAME:8080/pet/1
curl -XDELETE $CONJUR_MASTER_HOST_NAME:8080/pet/2
curl -XDELETE $CONJUR_MASTER_HOST_NAME:8080/pet/3
curl -XDELETE $CONJUR_MASTER_HOST_NAME:8080/pet/4
