#!/bin/bash 
source ./vault-sync.config

docker exec conjur-cli conjur authn login -u admin -p $CONJUR_ADMIN_PASSWORD
sed -e "s#{{ VAULT_NAME }}#$VAULT_NAME#g" vault-sync-policy.template |
sed -e "s#{{ SYNC_HOST }}#$SYNC_HOST#g" > vault-sync-policy.yml
docker cp vault-sync-policy.yml conjur-cli:/policy
docker exec conjur-cli conjur policy load root /policy/vault-sync-policy.yml
echo "API key for $SYNC_HOST:" $(docker exec conjur-cli conjur host rotate_api_key -h $SYNC_HOST)
