#!/bin/bash

source lib/util
source spring-demo.config

./bin/build
./stop

begin "Starting app container..."
{
  docker-compose up -d demo-pg

  docker exec $CLI_CONTAINER_NAME bash -c "echo yes | conjur init -u \"https://$CONJUR_MASTER_HOST_NAME:$CONJUR_MASTER_PORT\" -a $CONJUR_ACCOUNT --force=true"
  docker exec $CLI_CONTAINER_NAME conjur authn login -u admin -p $CONJUR_ADMIN_PASSWORD
} &> "${LOGBUFFER}"
finish

begin "Loading policy files"
{
  docker cp ./policy/hello.yml $CLI_CONTAINER_NAME:/policy
  docker exec -it $CLI_CONTAINER_NAME bash -c "
    conjur policy load root /policy/hello.yml
    conjur variable values add spring-apps/hello/pg/username postgres
    conjur variable values add spring-apps/hello/pg/password postgres
    conjur variable values add spring-apps/hello/secret $(openssl rand -hex 12)
  "
} &> "${LOGBUFFER}"
finish

begin "Starting the demo service"
{
  CONJUR_AUTHN_API_KEY=$(docker exec -it $CLI_CONTAINER_NAME conjur host rotate_api_key -h spring_demo | tr -d '\r\n')
  echo $CONJUR_AUTH_API_KEY
  docker-compose up -d hello
  docker cp $CONJUR_CERT_FILE hello:/etc/
  docker cp ./secrets.yml hello:/
  docker cp target/hello-0.1.0.jar hello:/
} &> "${LOGBUFFER}"
finish
docker-compose exec hello bash
