#!/bin/bash 
set -eou pipefail

main() {

  # Generate private key for client and certificate signing request (CSR)
  if [ ! -f ./client.key ]; then
    openssl genrsa -out ./client.key 2048
    chmod 400 ./client.key
  fi

  openssl req -new -sha256 \
        -subj "/C=US/ST=./L=./O=./CN=client" \
        -key ./client.key \
        -out ./client.csr

  # Authenticate with Conjur as a host
  encoded_login=$(urlencode "host/$MTLS_CLIENT_LOGIN")
  token=$(curl -s -X POST \
		--cacert "$CONJUR_CERT_FILE" \
		-d $CONJUR_AUTHN_API_KEY \
          	"$CONJUR_APPLIANCE_URL/authn/$CONJUR_ACCOUNT/$encoded_login/authenticate" \
	          | base64 | tr -d '\r\n')

  # Request a certificate from the CA configured in Conjur
  ca_response=$(curl -s \
		-X POST \
		--cacert "$CONJUR_CERT_FILE" \
		-d "ttl=P1D" \
		--data-urlencode "csr@./client.csr" \
                -H "Authorization: Token token=\"$token\"" \
                "$CONJUR_APPLIANCE_URL/ca/$CONJUR_ACCOUNT/$CA_SERVICE_ID/sign")

  echo $ca_response | jq -r .certificate
  echo $ca_response | jq -r .certificate > ./client.crt
}

urlencode() {
        local str=$1; shift
        str=$(echo $str | sed 's= =%20=g')
        str=$(echo $str | sed 's=/=%2F=g')
        str=$(echo $str | sed 's=:=%3A=g')
	echo $str
}

main "$@"
